# Generated by Django 6.0.5 on 2026-05-13 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main_app', '0002_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.major'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_by_students', to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('advisor', 'Advisor')], default='student', max_length=20),
        ),
    ]
