# Generated by Django 6.0.5 on 2026-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_advisorprofile_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
