# Generated by Django 6.0.5 on 2026-05-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_advisorprofile_name_studentprofile_gpa_and_more'),
        ('main_app', '0002_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='budget_level',
            field=models.CharField(choices=[('low', 'Low Budget (150-350 BD)'), ('medium', 'Medium Budget (351-700 BD)'), ('high', 'Excellent Budget (701+ BD)')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='entry_semester',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], default='fall', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='entry_year',
            field=models.PositiveIntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_semesters_per_year',
            field=models.IntegerField(choices=[(2, '2 Semesters'), (3, '3 Semesters')], default=3),
        ),
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_type', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_courses', models.ManyToManyField(blank=True, to='main_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_semesters', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
