# Generated by Django 6.0.5 on 2026-05-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_budget_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.advisorprofile'),
        ),
    ]
